version: '3'

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_USERNAME: root
      MONGO_PASSWORD: 123456

volumes:
  mongodb_data:
    driver: local
